- name: create es user
  user: name=es password={{password}}
  vars:
    # created with:
    # python -c 'import crypt; print crypt.crypt("This is my Password", "$1$SomeSalt$")'
    # >>> import crypt
    # >>> crypt.crypt('wisedu123', '$1$bigrandomsalt$')
    # '$1$bigrando$wzfZ2ifoHJPvaMuAelsBq0'
    password: $1$bigrando$wzfZ2ifoHJPvaMuAelsBq0
- name: mkdir directory for elasticsearch data
  file: dest=/esdata mode=0755 state=directory owner=es group=es
- name: copy and unzip es
  #unarchive module owner and group only effect on directory.
  unarchive: src=elasticsearch-2.3.3.tar.gz dest=/usr/local/
- name: install memory configuration file for es
  template: src=elasticsearch.in.sh.j2 dest=/usr/local/elasticsearch-2.3.3/bin/elasticsearch.in.sh owner=es group=es
- name: install configuration file for es
  template: src=elasticsearch.yml.j2 dest=/usr/local/elasticsearch-2.3.3/config/elasticsearch.yml owner=es group=es
- name: mkdir directory for elasticsearch-analysis-ik plugin
  file: dest=/usr/local/elasticsearch-2.3.3/plugins/ik mode=0755 state=directory owner=es group=es
- name: copy and unizp elasticsearch-analysis-ik plugin
  unarchive: src=elasticsearch-analysis-ik-1.9.3.zip dest=/usr/local/elasticsearch-2.3.3/plugins/ik
- name: change owner and group
  #recurse=yes make all files in a directory changed.
  file: path=/usr/local/elasticsearch-2.3.3 owner=es group=es recurse=yes
- name: start es
  remote_user: es
  shell: su - es -c '/usr/local/elasticsearch-2.3.3/bin/elasticsearch -d'
  #command: /usr/local/elasticsearch-2.3.3/bin/elasticsearch -d
  #become: true
  #become_method: su
  #become_user: es
  tags:
  - start
